feat: Support HTTPS endpoints
pivotal/cloud-service-broker pull request #1084
Opened 2024-09-03 12:41 UTC by ifindlay-cci

### Checklist:

* [ ] Have you added or updated tests to validate the changed functionality?
* [ ] Have you added Release Notes in the docs repositories?
* [ ] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

2024-09-04 11:58 UTC, zucchinidev commented on internal/testdrive/broker_start.go
> +				http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
issue: Avoid modifying the global `http.DefaultTransport` directly. Instead, create a custom transport.

2024-09-04 12:44 UTC, zucchinidev requested changes

2024-09-04 12:44 UTC, zucchinidev commented on internal/testdrive/broker_start.go
>  	for {
```suggestion
	scheme := "http"
	transport := &http.Transport{}
	for _, envVar := range cmd.Env {
		if strings.HasPrefix(envVar, "TLS_") {
			http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
			scheme = "https"
			break
		}
	}

	for {
		httpClient := &http.Client{Transport: transport}
		response, err := httpClient.Head(fmt.Sprintf("%s://localhost:%d", scheme, port))
```

2024-09-04 12:44 UTC, zucchinidev commented on internal/testdrive/broker_start.go
> +		}
```suggestion
		if !isValid {
		       // If the isValid parameter is false, the server private key is intentionally corrupted
		       // by modifying one of its bytes.
			serverPrivKey[10] = 'a'
		}
```

2024-09-04 12:44 UTC, zucchinidev commented on internal/testdrive/broker_start.go
> +	caPEM, _ := encodeKeyPair(caBytes, x509.MarshalPKCS1PrivateKey(caPrivKey))
issue (non-blocking): the PEM-encoded CA certificate is not being used. The code is not necessary, by removing it, we will improve the readability and the public API of the createCAKeyPair function

2024-09-04 12:44 UTC, zucchinidev commented on internal/testdrive/broker_start.go
> +	return certPEM, certPrivKeyPEM
thoughts: I prefer to declare the variable using the semantic value and return it with the semantic pointer. If the body of the functions grows, the readability gets worse.

2024-09-04 12:44 UTC, zucchinidev commented on cmd/serve.go
> +	logger.Info("tlsKey", lager.Data{"tlsKey": tlsKey})
issue: we want to avoid logging sensitive data.

2024-09-04 12:44 UTC, zucchinidev commented on cmd/serve.go
> +		_ = httpServer.ListenAndServe()
```suggestion
		err := httpServer.ListenAndServe()
	        if err != nil {
		        logger.Fatal("Failed to start broker without TLS", err)
	        }
```

2024-09-04 14:13 UTC, nouseforaname commented on internal/testdrive/broker_start.go
> +				http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
for tests?

2024-09-04 14:13 UTC, nouseforaname commented on internal/testdrive/broker_start.go
> +				http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
again, for tests?

2024-09-04 14:14 UTC, nouseforaname commented on cmd/serve.go
> +	logger.Info("tlsKey", lager.Data{"tlsKey": tlsKey})
thats a path

2024-09-04 14:15 UTC, nouseforaname commented on cmd/serve.go
> +		_ = httpServer.ListenAndServe()
we cannot fatal here, as ListenAndServe always returns a non nil error

2024-09-05 08:50 UTC, nouseforaname commented on internal/testdrive/broker_start.go
> +	return certPEM, certPrivKeyPEM
I'm not sure I understand how the readability will get better by returning a pointer?

2024-09-10 10:23 UTC, merged